// <auto-generated />
using ACME.MicrosoftCA.Gateway.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ACME.MicrosoftCA.Gateway.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20180319210921_000_CreateDB")]
    partial class _000_CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ACME.MicrosoftCA.Gateway.Models.Data.ReplayNonce", b =>
                {
                    b.Property<string>("Nonce")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("IssedAt");

                    b.HasKey("Nonce");

                    b.ToTable("IssuedNonces");
                });
#pragma warning restore 612, 618
        }
    }
}
